name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chip8
    steps:
      - uses: actions/checkout@v4
      - name: Pick Rust channel
        run: rustup update 1.80 && rustup default 1.80
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
